version: '3.8'

services:
  snake-game:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    container_name: snake-game
    ports:
      - "8080:8080"
    volumes:
      - snake-data:/app/BOOT-INF/classes/static
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - TZ=UTC
      # JVM tuning
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:+UseStringDeduplication
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/game"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - snake-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  snake-data:
    name: snake-game-data

networks:
  snake-network:
    name: snake-game-network
    driver: bridge
