version: '3.8'

services:
  snake-game:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: snake-game
    ports:
      - "8080:8080"
    volumes:
      - type: volume
        source: snake-data
        target: /app/logs
      - type: bind
        source: ./src/main/resources/static
        target: /app/BOOT-INF/classes/static
        read_only: true
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - TZ=UTC
      # JVM and GC tuning
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+UseG1GC -XX:+UseStringDeduplication -Xms256m -Xmx512m
    deploy:
      resources:
        limits:
          memory: 768M
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/game"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - snake-network
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"

volumes:
  snake-data:
    name: snake-game-data

networks:
  snake-network:
    name: snake-game-network
    driver: bridge
